server:
  port: 3030

spring:
  datasource:
    username: root
    password: bjtu2024
    url: jdbc:mysql://39.106.39.209:3306/tiktok?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
  data:
    redis:
      port: 6379
      host: 39.106.39.209

  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, info, prometheus

logging:
  config: classpath:logback.xml

jwt:
  secret: 1234567890123456
  expirationTime: 604800
  issuer: springboot3-security
  header: Authorization
  tokenHead: Bearer

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
